#! /usr/bin/env python
#coding:utf-8

import random

num=random.randint(1,101)

guess=0

while True:
    num_input=raw_input('please input one interger that is in 1 to 100:')
    guess+=1

    if not num_input.isdigit():
        print 'Please input interger.'
    elif int(num_input)<0 or int(num_input)>=100:
        print 'The number should be in 1 to 100.'
    else:
        if num==int(num_input):
            print 'OK,you are good. It is only %d times, then you successed.' % guess
            break
        elif num>int(num_input):
            print 'your number is more less.'
        elif num<int(num_input):
            print 'your number is bigger.'
        else:
            print 'There is somehting bad, I will not work.'
